### ISSUE TITLE
systemd config files in /etc overlayfs seem to actually survive system updates

### ISSUE THREAD

**Issue by coolbho3k** [randombk/steamos-teardown#1]
In `partitions.md`, you write that `/etc is writable, but not persistent`.

However, I edited `sdcard-mount@.service` in `/etc/systemd/system`, which writes to the overlayfs (to point to a mounting script which supports btrfs). And my changes _always_ survive a system update. I've done this at least twice, as I've installed a bigger SSD in my Deck and started afresh.

I actually can't see _how_ the configuration survives given that the overlayfs upperdir seems to toggle between partitions when you do a system update, but it does. Anecdotally, enabling `sshd` via `systemctl` persists across system updates too, so any edits to the upperdir _seem_ to be persisted.

How this works is maybe worth investigating and documenting.

**Comment by randombk** [comment]
I'm actually about to publish the section on system updates, and I think that might explain part of what's going on. I still need to confirm a few things though - ETA tomorrow.

**Comment by randombk** [comment]
But briefly:

1. I made a mistake - those partitions aren't just for the `/etc` overlay, but for all of `/var`. The `/etc` overlay upper is stored on `/var`.

2. During system update, the system writes the update to the non-active side, then switches to booting from the other side on next reboot.

3. As part of that update process, the non-active `/var` partition is **reformatted** and the contents of the current `/var` partition is rsynced over.

Thus, both `/var` and `/etc` are actually writable and persistent. Tbh this whole wipe-and-copy-over process makes me nervous, though it looks quite sturdy. It does mean the 2nd OS copy is less about redundancy and more about being reserved space to implement the atomic update mechanism.

**Comment by coolbho3k** [comment]
Nicely found. Where is the update script you're looking at?

**Comment by randombk** [comment]
Have a look!

https://github.com/randombk/steamos-teardown/blob/master/docs/system-updates.md
